# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29a9a2a28fb1ab17881126de78a80e60ff13024da23e52aa821795696b1145128936471fb87de56ae01f4cf2bb9474606f6443b4c897c54f4115491ecca39c13

test:
  secret_key_base: 0a9909a136d5089f304583c66ebcd59eb0f2379019381a5eda30225ab3858a0a974ee8470350c82c2ac85d3ae073885a829a0abc5d38c4db51c3836ec144fe93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
